[package]
name = "rust-advent-of-code"
version = "0.1.0"
authors = ["Jonathan Pallant <jonathan.pallant@cambridgeconsultants.com>"]

[dependencies]
failure = "0.1.1"
md5 = "0.3.6"
regex = "1"
colored = "*"
